<?php
/**
 * @file
 * Drupal needs this blank file.
 */
 
/**
 * Implements hook_menu()
 */
function site_overrides_menu() {
	$items['admin/config/system/overrides'] = array(
		'title' => 'Site Overrides',
		'description' => 'Configuration for various overrides of default Drupal behavior',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('site_overrides_form'),
		'access arguments' => array('administer content types'),
		'type' => MENU_NORMAL_ITEM,
	);
	
	return $items;
}

/**
 * Page callback: Site Overrides Settings
 *
 * @see site_overrides_menu
 */
function site_overrides_form($form, &$form_state) {
    
    $form['site_overrides_send_sys_emails_to'] = array(
		'#type' => 'textfield',
		'#title' => t('Send System E-mails to'),
		'#default_value' => variable_get('site_overrides_send_sys_emails_to', variable_get('site_mail', '')),
		'#size' => 30,
		'#description' => t('The e-mail address that system e-mails should be sent to. Defaults to the e-mail address set in Site Information.'),
		'#required' => TRUE,
	);
	
	return system_settings_form($form);
}

/**
 * Save settings from configuration page
 */
function site_overrides_form_submit($form, &$form_state) {
	variable_set('site_overrides_send_sys_emails_to', $form_state['values'][site_overrides_send_sys_emails_to]);
}

/**
 * Override the default e-mail address used to send system e-mails ONLY
 */
function site_overrides_mail_alter(&$message) {
	if ($message['id'] == 'user_register_pending_approval') {
		UserRegisterPendingApproval_Override($message);
	}
	
	return;
}

/**
 * Override for UserRegisterPendingApproval
 */
function UserRegisterPendingApproval_Override(&$message) {
	// get the overridden to e-mail address, or default to the site-email address
	$toEmail = variable_get('site_overrides_send_sys_emails_to', variable_get('site_mail', ''));
	
	// set the to e-mail address
	$message['to'] = $toEmail;
	
	return;
}

?>